name: Deploy PuzzleScript to Gist
on:
  push:
    paths:
      - 'script.txt'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.TOKEN }}
        gist_id: 9044a8b4cf78d6ebd16020bbc1dadb25
        gist_file_name: script.txt
        file_path: script.txt
